# Matrices and Matrix Operations

This function introduces various ways to create
matrices and how to use them in TensorFlow

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

Start a graph session

In [2]:
sess = tf.Session()

### Declaring matrices

Identity Matrix:

In [3]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


2x3 random norm matrix:

In [5]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[ 1.97524643  1.2096225   1.47223914]
 [-1.73861492 -0.82322854  0.56155652]]


2x3 constant matrix:

In [6]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


3x2 random uniform matrix:

In [7]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[  6.99557185e-01   4.35436010e-01]
 [  3.22627306e-01   6.39427900e-01]
 [  1.61767006e-04   7.19993353e-01]]


Create matrix from np array:

In [9]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


### Matrix Operations

Matrix addition/subtraction:

In [10]:
print(sess.run(A+B))
print(sess.run(B-B))

[[ 5.55259609  4.3744812   5.02576828]
 [ 5.05264664  4.8369832   5.88435555]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Matrix Multiplication:

In [11]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


Matrix Transpose:

In [12]:
print(sess.run(tf.transpose(C)))

[[ 0.36366546  0.66778398  0.78392828]
 [ 0.77442658  0.72467291  0.07487059]]


Matrix Determinant:

In [13]:
print(sess.run(tf.matrix_determinant(D)))

-38.0


Matrix Inverse:

In [14]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


Cholesky Decomposition:

In [15]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Eigenvalues and Eigenvectors:  We use `tf.self_adjoint_eig()` function, which returns two objects, first one is an array of eigenvalues, the second is a matrix of the eigenvectors.

In [17]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]
